### ISSUE TITLE
Improve input data preprocessing

### ISSUE THREAD

**Issue by tmshv** [Massugunaen/names-changer#14]
https://github.com/Massugunaen/names-changer/blob/c2d31598080d275354da590a1dae87b347fb59f7/main.py#L10

With usage of methods from [stdlib](https://docs.python.org/3/library/stdtypes.html#str.strip)

**Comment by modernpacifist** [comment]
It actually works like as it should be, I think.
Spaces in list are counted as empty objects and "remove_spaces" function removes empty objects in lists.
So I don't know what to change here, or needed to be changed.

**Comment by tmshv** [comment]
Just remove unnecessary lines of code and replace it with functionality of stdlib.

**Comment by modernpacifist** [comment]
Can not do, this function removes spaces from list of strings.
It is more accurate, I think.
