### ISSUE TITLE
The question

### ISSUE THREAD

**Issue by tmshv** [Massugunaen/names-changer#3]
I appreciate your desire to invent the wheel, but it is not necessary in this task. All you need to do is `pip install petrovich`.

**Comment by modernpacifist** [comment]
Ty so much, I tried looking for proper module, but didn't find any.
So had to turn to inventing the wheel...

**Comment by modernpacifist** [comment]
Actually, during my research I ran into something called "petrovich", but because of its' name thought it was kind of a joke)
